repos:
  - repo: local
    hooks:
      - id: ty-type-check
        name: ty type checking
        entry: ./scripts/run-ty.sh
        language: system
        files: \.py$
        pass_filenames: false
        args: [.]
      - id: ruff
        name: ruff
        entry: ./scripts/run-ruff.sh
        language: system 
        files: \.py$
        pass_filenames: false
        args: [.]