repos:
  - repo: local
    hooks:
      - id: ty-type-check
        name: ty type checking
        entry: /Users/imgabgi/.local/bin/uvx ty check
        language: system
        files: \.py$
        pass_filenames: false
        args: [.]
      - id: ruff
        name: ruff
        entry: /Users/imgabgi/.local/bin/uvx ruff check
        language: system 
        files: \.py$
        pass_filenames: false
        args: [.]